### ISSUE TITLE
Fire Base Connect with Fire Fox OS?

### ISSUE THREAD

**Issue by liubrian** [PSUCapstoneA/firefox-im#15] opened 2013-06-08 21:57 UTC
Just open index1.html with two browser. They were able to talk to each other. 

However, if I open index1.html in a browser, and open our demo OS simulator. It doesn't work.

I feel like the OS S is not connect to the outside world.

**Comment by PSUCapstoneA** [comment] 2013-06-19 03:09
Duplicate of #14

**Closed as completed by PSUCapstoneA** 2013-06-19 03:09 UTC
Labels: bug
